### ISSUE TITLE
Build issue under Arch

### ISSUE THREAD

**Issue by armandocerna** [hugegreenbug/libgestures#2]
Thanks for all your excellent work! 

I'm seeing the following error after trying to install libgestures from AUR (https://aur.archlinux.org/packages/libgestures/):

pacaur -S libgestures

g++ -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -std=gnu++11 -fno-exceptions -fno-strict-aliasing -fPIC -Wall -Wclobbered -Wempty-body -Werror -Wignored-qualifiers -Wmissing-field-initializers -Wmissing-format-attribute -Wmissing-noreturn -Wsign-compare -Wtype-limits -D__STDC_FORMAT_MACROS=1 -D_FILE_OFFSET_BITS=64 -DGESTURES_INTERNAL=1 -Iinclude `pkg-config --cflags glib-2.0` -O3 -DVCSID="\"2.0.4\"" --coverage -ftest-coverage -fprofile-arcs -I/usr/include/jsoncpp -MMD -c -o obj/tap_to_click_fix_filter_interpreter.o src/tap_to_click_fix_filter_interpreter.cc
src/tap_to_click_fix_filter_interpreter.cc:5:66: fatal error: gestures/include/tap_to_click_fix_filter_interpreter.h: No such file or directory
compilation terminated.
Makefile:177: recipe for target 'obj/tap_to_click_fix_filter_interpreter.o' failed
make: *** [obj/tap_to_click_fix_filter_interpreter.o] Error 1
==> ERROR: A failure occurred in build().

**Comment by hugegreenbug** [comment]
Oops. Fixed.

**Comment by armandocerna** [comment]
Worked great! Thanks!

Armando
